version: 2

project_name: natsmith

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: migrate-nats-kv
    main: ./cmd/migrate-nats-kv
    binary: migrate-nats-kv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: migrate-nats-objects
    main: ./cmd/migrate-nats-objects
    binary: migrate-nats-objects
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

release:
  github:
    owner: sabinadams
    name: natsmith
