version: 2

project_name: natsmith

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: natsmith
    main: ./cmd/natsmith
    binary: natsmith
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

brews:
  - name: natsmith
    repository:
      owner: sabinadams
      name: natsmith
    directory: Formula
    homepage: "https://sabinadams.github.io/natsmith/"
    description: "CLI tooling for NATS and JetStream"
    license: "MIT"
    test: |
      system "#{bin}/natsmith", "-h"

release:
  github:
    owner: sabinadams
    name: natsmith
