# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natsmith < Formula
  desc "CLI tooling for NATS and JetStream"
  homepage "https://sabinadams.github.io/natsmith/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sabinadams/natsmith/releases/download/v0.2.0/natsmith_0.2.0_darwin_amd64.tar.gz"
      sha256 "6808b83730365f09ca1488dade6b489087f89213d03cd24939ecf9b8570b3a65"

      define_method(:install) do
        bin.install "natsmith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sabinadams/natsmith/releases/download/v0.2.0/natsmith_0.2.0_darwin_arm64.tar.gz"
      sha256 "01af4eeb7f6612ac63c7dce055b9448398d705ac9aade931e082342db813cf9e"

      define_method(:install) do
        bin.install "natsmith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sabinadams/natsmith/releases/download/v0.2.0/natsmith_0.2.0_linux_amd64.tar.gz"
      sha256 "d99558ab8bfcbe678fda59490a8cca1a8ae51dcf6d5e4c2c2cf4ae4782daf489"
      define_method(:install) do
        bin.install "natsmith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sabinadams/natsmith/releases/download/v0.2.0/natsmith_0.2.0_linux_arm64.tar.gz"
      sha256 "b223f1244f7fb3116ba3850026e94299c499ec9035ca2ea1c5c9b1d9fa9dc0de"
      define_method(:install) do
        bin.install "natsmith"
      end
    end
  end

  test do
    system "#{bin}/natsmith", "-h"
  end
end
