#!/usr/bin/env sh
# Write the latest published GitHub release version for the docs site.
# Usage: scripts/fetch-release-version.sh

set -e

REPO="${NATSITH_REPO:-sabinadams/natsmith}"
root="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
out="${root}/website/lib/version.generated.js"

api="https://api.github.com/repos/${REPO}/releases/latest"
json="$(curl -fsSL -H "Accept: application/vnd.github+json" "$api")" ||
  { echo "fetch-release-version: could not fetch ${api}" >&2; exit 1; }

tag="$(printf '%s\n' "$json" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\(v[^"]*\)".*/\1/p')"
[ -n "$tag" ] || { echo "fetch-release-version: could not parse tag_name" >&2; exit 1; }

version="${tag#v}"

mkdir -p "$(dirname "$out")"
cat >"$out" <<EOF
// Generated by scripts/fetch-release-version.sh — do not edit.
export const version = '${version}'
export const tag = '${tag}'
EOF

echo "fetch-release-version: ${tag}" >&2
